#!/bin/sh

#!/bin/bash
# This script converts wav files into mp3. You can even choose the bitrate for your mp3 file.
#

if [ $# -eq 0 ]
then
        echo "Error - bitrate number is missing"
        echo "Syntax: wav2mp3 (bitrate number)"
        echo "For MPEG1 bitrate  number is 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320"
        echo "Example: wav2mp3 128     (will convert all .wav files in the current directory to 128 bitrate .mp3 files)"
exit 1
fi

NUM=`ls -1 *.wav | wc -l`
echo '\033[1m' Found $NUM files to encode... '\033[0m'

for i in $(seq 1 $NUM)
 do
  WAV=`ls -1 *.wav | head -n $i | tail -n 1`
  MP3=`echo $WAV | sed s/.wav/.mp3/g`
  echo '\033[1m' Encoding file \#$i: \"$WAV\" to \"$MP3\" at $1 bps VBR'\033[0m'
  lame -m s -h -v --vbr-new -b $1 "$WAV" "$MP3"
 done

echo '\033[1m' All done! '\033[0m'
